# -*- coding: utf-8 -*-
"""yelp2018-code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VuglKbDgJFjPDRCOkBj3eFl3omyfxEoq
"""

import numpy as np

import random
from collections import defaultdict


# ======================
# 1. LOAD + SPLIT (GIỮ PATH CŨ)
# ======================
import random
def write_user_items(path, user_items, skip_empty=True):
    with open(path, "w") as f:
        for u in sorted(user_items.keys()):
            items = user_items[u]

            if skip_empty and len(items) == 0:
                print("skip empty")
                continue

            line = [str(u)] + list(map(str, items))
            f.write(" ".join(line) + "\n")


def load_data_with_valid(
    train_path,
    test_path,
    train_out_path,
    valid_out_path,
    valid_ratio=0.1,
    seed=2020
):
    rng = random.Random(seed)

    user_train = {}
    user_valid = {}
    user_test = {}
    max_item = 0

    train_interactions = 0
    valid_interactions = 0
    test_interactions = 0

    # ===== TRAIN FILE: split thành TRAIN + VALID =====
    with open(train_path, "r") as f:
        for line in f:
            parts = list(map(int, line.strip().split()))

            # Format: user_id item1 item2 item3 ...
            if len(parts) <= 1:
                continue

            u = parts[0]
            items = parts[1:]

            rng.shuffle(items)

            if len(items) == 1:
                # User chỉ có 1 item thì giữ trong train
                # để user không bị mất history
                user_train[u] = items
                user_valid[u] = []
            else:
                # train : valid = 7 : 1
                n_valid = max(1, int(len(items) * valid_ratio))

                # Không cho valid lấy hết item
                n_valid = min(n_valid, len(items) - 1)

                user_valid[u] = items[:n_valid]
                user_train[u] = items[n_valid:]

                valid_interactions += len(user_valid[u])

            train_interactions += len(user_train[u])
            max_item = max(max_item, max(items))

    # ===== GHI TRAIN + VALID RA FILE TXT =====
    write_user_items(train_out_path, user_train, skip_empty=True)
    write_user_items(valid_out_path, user_valid, skip_empty=True)

    # ===== TEST (GIỮ NGUYÊN) =====
    with open(test_path, 'r') as f:
        for line in f:
            parts = list(map(int, line.strip().split()))

            if len(parts) <= 1:
                continue

            u = parts[0]
            items = parts[1:]

            # Nếu evaluation của bạn dùng 1 ground-truth item
            user_test[u] = items
            test_interactions += len(items)

            max_item = max(max_item, max(items))

    num_items = max_item + 1

    print("===== DATA STAT =====")
    print(f"Train users: {len(user_train)}")
    print(f"Valid users: {sum(1 for u in user_valid if len(user_valid[u]) > 0)}")
    print(f"Test users : {len(user_test)}")
    print(f"Train interactions: {train_interactions}")
    print(f"Valid interactions: {valid_interactions}")
    print(f"Test interactions : {test_interactions}")
    print(f"Total interactions : {test_interactions + valid_interactions + train_interactions}")
    print(f"Num items: {num_items}")
    print("=====================")

    return user_train, user_valid, user_test, num_items
# ======================
# 6. RUN
# ======================
train_path = "./train_val.txt"
test_path  = "./test.txt"
train_out_path = "./train.txt"
valid_out_path =  "./validation.txt"
    
user_train, user_valid, user_test, num_items = load_data_with_valid(train_path, test_path, train_out_path, valid_out_path)
